<AddressesList@Screen>:
    name: "AddressesList"

    RecycleView:
        id: addresses_list
        viewclass: 'OneLineListItem'
        pos_hint: {"center_x": .5}

        RecycleBoxLayout:
            orientation: 'vertical'
            default_size: None, dp(50)
            default_size_hint: 1, None
            size_hint_y: None
            height: self.minimum_height
            spacing: dp(5)
            padding: dp(0), dp(5)
