# Coding: UTF-8

# Copyright (C) 2024 Michał Prędki
# Licensed under the GNU General Public License v3.0.
# Full text of the license can be found in the LICENSE and COPYING files in the repository.

#:import MapScreen mapscreen

<MapScreen@Screen>:
    name: "MapScreen"

    MDIconButton:
        theme_icon_color: "Custom"
        icon_color: 0, 0, 0, .87

        pos_hint: {"right": .2, "top": .08}
        icon: "crosshairs-gps"
        on_release: root.center_map_widget_on_user_location()
